# Numpy

파이썬에서 행렬관련 계산을 빠르게 해주는 패키지

ndarray: 행렬이라고 생각하면 된다.
nd는 n차원을 의미 (n dimensional)

주로 Tensorflow 나 pytorch, keras 등의 머신러닝 프레임워크에서 ndarray를 사용

## 1.Numpy 배열(Array) 생성하기

In [3]:
# 모듈 불러오기
import numpy as np

* np.array()
    * 입력받은 파이썬 리스트를 ndarray 형태로 변형

In [7]:
# 1차원 배열 생성
array = np.array(["A","B","C","D","E","F"])
array

array(['A', 'B', 'C', 'D', 'E', 'F'], dtype='<U1')

In [8]:
print(array.shape) # 차원의 요소 개수
print(array.ndim) # 차원
print(array.dtype) # data type -> 공통적인 데이터 타입

(6,)
1
<U1


In [9]:
# 2차원 배열 생성
array2 = np.array(
    [["A","B","C"],
     ["D","E","F"]])
array2

array([['A', 'B', 'C'],
       ['D', 'E', 'F']], dtype='<U1')

In [21]:
print(array2.shape) # 차원의 요소 개수
print(array2.ndim) # 차원
print(array2.dtype) # data type -> 공통적인 데이터 타입 / U1 -> 문자열

(2, 3)
2
<U1


In [19]:
# 3차원 배열 생성
array3 = np.array([[["A","B","C"],["D","E","F"]], [["A","B","C"],["D","E","F"]]])
array3

array([[['A', 'B', 'C'],
        ['D', 'E', 'F']],

       [['A', 'B', 'C'],
        ['D', 'E', 'F']]], dtype='<U1')

In [22]:
print(array3.shape) # 차원의 요소 개수
print(array3.ndim) # 차원
print(array3.dtype) # data type -> 공통적인 데이터 타입

(2, 2, 3)
3
<U1


* np.arange()
    * 파이썬의 range 함수와 같지만 ndarray 객체를 생성

In [18]:
# arange 함수를 이용한 배열 생성
array4 = np.arange(5)
print(array4)
array4 = np.arange(0,15,3)
print(array4)

[0 1 2 3 4]
[ 0  3  6  9 12]


In [28]:
print(array4.shape) # 차원의 요소 개수
print(array4.ndim) # 차원
print(array4.dtype) # data type -> 공통적인 데이터 타입

(5,)
1
int64


## 2.Numpy 형상 관련 함수

In [24]:
# astype() - ndarray 타입변환
array5 = np.array([1,2,3,4,5])
print(array5.dtype)

int32


In [ ]:
* astype()
    * ndarray의 타입을 변경 (int -> str, str -> int)

In [25]:
# int to float
array5 = array5.astype(np.float64)
print(array5.dtype)

float64
<U1
int64


In [26]:
# str to int
array6 = np.array(["1","2","3"])
print(array6.dtype)

array6 = array6.astype(np.int64)
print(array6.dtype)

<U1
int64


형상 관련 함수

* np.reshape()
    * 행렬의 차원을 변경하고자 할 때 사용

In [27]:
# reshape() - ndarray 차원과 크기를 변경
array7 = np.arange(5)
print(array7)

[0 1 2 3 4]


In [6]:
array7.reshape(-1, 1) # 행에 -1을 넣으면 열을 따라가겠다는 의미.
print(array7)
print(array7.shape) # (5,1) => 5행 1열

NameError: name 'array7' is not defined

In [30]:
array7 = array7.reshape(1, -1)
print(array7)
print(array7.shape)

[[0 1 2 3 4]]
(1, 5)


In [31]:
array8 = np.arange(10)
print(array8)

array8 = array8.reshape(2,5)
print(array8)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
array8 = array8.reshape(5,2)
print(array8)

## 3.Numpy 인덱싱 & 슬라이싱

In [15]:
# 1차원 인덱싱
arr = np.arange(1, 10)
print(arr)
print(arr[5])
print(arr[-1])
print(arr[0:4])
print(arr[:])
print(arr > 7)
print(arr[arr>7])
print(arr[~(arr>7)])

[1 2 3 4 5 6 7 8 9]
6
9
[1 2 3 4]
[1 2 3 4 5 6 7 8 9]
[False False False False False False False  True  True]
[8 9]
[1 2 3 4 5 6 7]


In [17]:
# 2차원 인덱싱
arr2 = np.arange(1,10).reshape(3,3)

print(arr2)
print(arr2[0,0])
print(arr2[0,1])
print(arr2[2,2])
print(arr2[0:2, 0:2])
print(arr2[1:2, 0:3])
print(arr2[1:2, :])
print(arr2[[0,1], 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
9
[[1 2]
 [4 5]]
[[4 5 6]]
[[4 5 6]]
[3 6]


## 4.Numpy 연산

* 사칙연산: np.add, np.substract, np.multiply, np.divide

* 최대값, 최소값: np.max, np.min

* 최대값, 최소값 위치 반환: np.argmax, np.argmin

* 내적: np.dot

https://numpy.org/doc/stable/reference/routines.math.html

In [35]:
# 배열 연산
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

In [36]:
add = np.add(arr1,arr2)
print(add)
print(arr1+arr2)

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [38]:
multiply = np.multiply(arr1,arr2)
print(multiply)
print(arr1*arr2)

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [47]:
np.max(arr1)
np.max(arr2)

8

In [42]:
np.argmax(arr1)
np.argmax(arr2)

3

In [48]:
np.min(arr1)
np.min(arr2)

5

In [43]:
np.argmin(arr1)
np.argmin(arr2)

0

In [46]:
# 행렬의 내적
arr1.dot(arr2)

array([[19, 22],
       [43, 50]])

https://mblogthumb-phinf.pstatic.net/MjAxOTEyMzBfMjgz/MDAxNTc3NjgzOTQxOTM2.lWWi4vZFiZ4AD_2hUyKMZxGmzKtX1FSjPha5VWfDgPkg.20o03tZVKH8aOS-lGEpVeSDt7kyfwuJ1daSCJdsUeW4g.JPEG.cni1577/SE-5fdd2822-a657-4e61-93ce-b0713c37ade5.jpg?type=w800